language: node_js
node_js:
  - node
  - "lts/*"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
  - yarn test
deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
